// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55Wvq6f_VT3dcnh5dtaq_DVZ5TG1cTSU',
    appId: '1:52737346374:web:1cd4efe6c569a4d2b33347',
    messagingSenderId: '52737346374',
    projectId: 'evently-52915',
    authDomain: 'evently-52915.firebaseapp.com',
    storageBucket: 'evently-52915.firebasestorage.app',
    measurementId: 'G-9B380RBXDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_q81gSlgfHHYPrJM8I2nAnZL8_ybr3Xk',
    appId: '1:52737346374:android:0f9d4df68dfbbe59b33347',
    messagingSenderId: '52737346374',
    projectId: 'evently-52915',
    storageBucket: 'evently-52915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwKRhbI7v0mga5CTynTnIHp5XYIbT52FE',
    appId: '1:52737346374:ios:03e48bbe0db6993cb33347',
    messagingSenderId: '52737346374',
    projectId: 'evently-52915',
    storageBucket: 'evently-52915.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwKRhbI7v0mga5CTynTnIHp5XYIbT52FE',
    appId: '1:52737346374:ios:03e48bbe0db6993cb33347',
    messagingSenderId: '52737346374',
    projectId: 'evently-52915',
    storageBucket: 'evently-52915.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB55Wvq6f_VT3dcnh5dtaq_DVZ5TG1cTSU',
    appId: '1:52737346374:web:eddc4603fe219687b33347',
    messagingSenderId: '52737346374',
    projectId: 'evently-52915',
    authDomain: 'evently-52915.firebaseapp.com',
    storageBucket: 'evently-52915.firebasestorage.app',
    measurementId: 'G-B626CERVJ1',
  );
}
